In [0]:
#Python - richest in terms of Data science and ML development libraries, packages and frameworks
#R

In [0]:
#Python understand the data type of variable based upon the declaration pattern
a = 'Bipul'       #string
b = 12            #Integer 
c = 2.0           #float

In [0]:
type(a)

str

In [0]:
#List - mutable
l =[4,5,6,7,8,8,2]
#tuple - immutable
t = (3,4,5,6,7,8)

In [0]:
l[2] = 'hello'

In [0]:
print(l)

[4, 5, 'hello', 7, 8, 8, 2]


In [0]:
t[2] = 'five'

TypeError: ignored

In [0]:
#Dictonary - values are stored against keys
d = {'name':'bipul', 'age':30, 'email':'bipul@abc.com'}
d

{'age': 30, 'email': 'bipul@abc.com', 'name': 'bipul'}

In [0]:
d['name']

'bipul'

In [0]:
#If-else
#Loops
#Functions
#Python Libraies and Packages for Data Science and ML
#Numpy  - Computing your n-dimensional mathematical data values
#Pandas 
#Matplotlib

In [0]:
import numpy as np
n = np.array([[3,4,5,6,7] , [2,4,5,6,7]])
print(n)

[[3 4 5 6 7]
 [2 4 5 6 7]]


In [0]:
##Attribute of numpy
print(n.shape)
print(n.size)
print(n.ndim)

(2, 5)
10
2


In [0]:
print(n[0,0])

3


In [0]:
#arange - array + range
#reshape - manipulating the shape
k = np.arange(0,36)
k = k.reshape(6,6)
k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
#k[row slicing index , column slicing index]
k[2:4,3:]

array([[15, 16, 17],
       [21, 22, 23]])

In [0]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
b = np.arange(5).reshape(1,5)
b

array([[0, 1, 2, 3, 4]])

In [0]:
#hstack
#vstack
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [0]:
c = np.array([5,8]).reshape(2,1)
c

array([[5],
       [8]])

In [0]:
np.hstack((a,c))

array([[0, 1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9, 8]])

In [0]:
#Dot product using numpy
a     #2*5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
c       #2*1

array([[5],
       [8]])

In [0]:
a = a.T
a

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [0]:
#Matrix dot product
np.dot(a,c)

array([[40],
       [53],
       [66],
       [79],
       [92]])

In [0]:
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.argmax(a))
print(np.argmin(a))
print(np.std(a))

45
9
0
4.5
9
0
2.8722813232690143


In [0]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
print(np.__version__)

1.18.2


In [0]:
#Pandas - Analytical tool
#It can be used to access, process or analyse the data sets
import pandas as pd 
#DataFrame
p = pd.DataFrame(a, columns = ['a','b'])

In [0]:
p

a  b
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [0]:
len(p['a'])

5

In [0]:
p['a'].max()

4

In [0]:
p['a'].mean()

2.0

In [0]:
p['a'].std()

1.5811388300841898

In [0]:
k = np.arange(4).reshape(2,2)

In [0]:
np.linalg.det(k)

-2.0

In [0]:
ipl = pd.read_csv(r'matches.csv')

In [0]:
ipl

id  season       city  ...          umpire1          umpire2 umpire3
0      1    2017  Hyderabad  ...      AY Dandekar         NJ Llong     NaN
1      2    2017       Pune  ...   A Nand Kishore           S Ravi     NaN
2      3    2017     Rajkot  ...      Nitin Menon        CK Nandan     NaN
3      4    2017     Indore  ...     AK Chaudhary    C Shamshuddin     NaN
4      5    2017  Bangalore  ...              NaN              NaN     NaN
..   ...     ...        ...  ...              ...              ...     ...
631  632    2016     Raipur  ...   A Nand Kishore     BNJ Oxenford     NaN
632  633    2016  Bangalore  ...     AK Chaudhary  HDPK Dharmasena     NaN
633  634    2016      Delhi  ...        M Erasmus    C Shamshuddin     NaN
634  635    2016      Delhi  ...        M Erasmus        CK Nandan     NaN
635  636    2016  Bangalore  ...  HDPK Dharmasena     BNJ Oxenford     NaN

[636 rows x 18 columns]

In [0]:
#How many toal matches ?
#Team won by maximum runs
#Team won by maximum wickets
#%ge of winner who did batting first
#team won by minimum runs
#team won by minimum wicket
#Total no. seasons in data
#Season with maximum no. of matches
#Most successfull team
#%ge of winner if they are also toss winner

In [0]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               636 non-null    int64  
 1   season           636 non-null    int64  
 2   city             629 non-null    object 
 3   date             636 non-null    object 
 4   team1            636 non-null    object 
 5   team2            636 non-null    object 
 6   toss_winner      636 non-null    object 
 7   toss_decision    636 non-null    object 
 8   result           636 non-null    object 
 9   dl_applied       636 non-null    int64  
 10  winner           633 non-null    object 
 11  win_by_runs      636 non-null    int64  
 12  win_by_wickets   636 non-null    int64  
 13  player_of_match  633 non-null    object 
 14  venue            636 non-null    object 
 15  umpire1          635 non-null    object 
 16  umpire2          635 non-null    object 
 17  umpire3         

In [0]:
len(ipl)

636

In [0]:
#Team won by maximum runs
#Team won by maximum wickets
ipl.loc[ipl['win_by_runs'].idxmax()]['winner']

'Mumbai Indians'

In [0]:
ipl.loc[632]
ipl.loc[0:2,'city':'team2']

city        date                team1                        team2
0  Hyderabad  2017-04-05  Sunrisers Hyderabad  Royal Challengers Bangalore
1       Pune  2017-04-06       Mumbai Indians       Rising Pune Supergiant
2     Rajkot  2017-04-07        Gujarat Lions        Kolkata Knight Riders

In [0]:
ipl.loc[43]['winner']

'Mumbai Indians'

In [0]:
ipl.loc[ipl['win_by_wickets'].idxmax()]['winner']

'Kolkata Knight Riders'

In [0]:
#Data Filter
ipl['win_by_wickets'].max()

10

In [0]:
ipl[ipl['win_by_wickets'] == ipl['win_by_wickets'].max()]['winner']

2            Kolkata Knight Riders
34                 Kings XI Punjab
71                 Deccan Chargers
119               Delhi Daredevils
183    Royal Challengers Bangalore
298               Rajasthan Royals
376                 Mumbai Indians
390            Chennai Super Kings
542    Royal Challengers Bangalore
590            Sunrisers Hyderabad
Name: winner, dtype: object

In [0]:
#%ge of winner who did batting first
len(ipl[ipl['win_by_wickets'] == 0])/len(ipl)

0.4669811320754717

In [0]:
#team won by minimum runs
#team won by minimum wicket

In [0]:
ipl[ipl['win_by_runs'] > 0]['win_by_runs'].min()

1

In [0]:
ipl[ipl['win_by_runs'] == 1]['winner']

58                  Mumbai Indians
105                Kings XI Punjab
163                Kings XI Punjab
344               Delhi Daredevils
350                 Mumbai Indians
518            Chennai Super Kings
598                  Gujarat Lions
614    Royal Challengers Bangalore
Name: winner, dtype: object

In [0]:
#Total no. seasons in data
#Season with maximum no. of matches
#Most successfull team
#%ge of winner if they are also toss winner

In [0]:
len(ipl['season'].unique())

10

In [0]:
ipl['season'].value_counts().idxmax()

2013

In [0]:
(ipl['winner'] == ipl['toss_winner']).sum()/len(ipl)

0.5110062893081762

In [0]:
ipl['winner'].value_counts().idxmax()

'Mumbai Indians'

In [0]:
x = pd.read_table('http://bit.ly/chiporders')
x.head()

order_id  ...  item_price
0         1  ...      $2.39 
1         1  ...      $3.39 
2         1  ...      $3.39 
3         1  ...      $2.39 
4         2  ...     $16.98 

[5 rows x 5 columns]

In [0]:
x.info()
#.str.contains() - it checks if any string value present or not
#.replace() - it replaces thr existing value
#.fillna()  - it fills the void points

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   order_id            4622 non-null   int64 
 1   quantity            4622 non-null   int64 
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB


In [0]:
#Find out all the data with chicken item present as item_name
x[x['item_name'].str.contains('Chicken')]

order_id  ...  item_price
4            2  ...     $16.98 
5            3  ...     $10.98 
11           6  ...      $8.75 
12           6  ...      $8.75 
13           7  ...     $11.25 
...        ...  ...         ...
4604      1828  ...      $8.75 
4615      1832  ...      $8.75 
4619      1834  ...     $11.25 
4620      1834  ...      $8.75 
4621      1834  ...      $8.75 

[1560 rows x 5 columns]

In [0]:
x['choice_description'] = x['choice_description'].fillna('abc')

In [0]:
x[x['choice_description'].str.contains('Vegetables')]

order_id  ...  item_price
7            4  ...     $11.75 
11           6  ...      $8.75 
13           7  ...     $11.25 
19          10  ...      $8.75 
39          19  ...     $11.75 
...        ...  ...         ...
4611      1830  ...     $11.25 
4612      1831  ...      $9.25 
4619      1834  ...     $11.25 
4620      1834  ...      $8.75 
4621      1834  ...      $8.75 

[722 rows x 5 columns]

In [0]:
x['item_price'].str.replace('$','').astype(float).mean()

7.464335785374397

In [0]:
#dtypes - to check the data type
#astype() - to convert the data type

In [0]:
x.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object