In [0]:
import pandas as pd
adv = pd.read_csv('Advertising.csv',index_col=0)

In [0]:
import numpy as np
X = adv[['TV','radio','newspaper']].values
Y = adv['sales'].values.reshape(-1,1)

In [56]:
X.shape

(200, 3)

In [0]:
#Using Linear regression algorithm calculate the 
#coefficients of best fit predictive line.
from sklearn.linear_model import LinearRegression
lmodel = LinearRegression()

In [58]:
#Training the model
lmodel.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [59]:
print(lmodel.intercept_)
print(lmodel.coef_)

[2.93888937]
[[ 0.04576465  0.18853002 -0.00103749]]


In [0]:
#Error Evaluation
#MAE - Mean Absolute error
#MSE - Mean squared error
#RMSE - Root mean squared error

#sales value
Y
#predicted sales value
Y_pred = lmodel.predict(X)

In [62]:
lmodel.predict([[50,43,10]])

array([[13.32353744]])

In [0]:
#0.047*50 + 7.03

In [29]:
a = np.arange(3,300).reshape(-1,1)
b = lmodel.predict(a)
import matplotlib.pyplot as plt
plt.scatter(X,Y)
#plt.plot(a,b,c='r')
plt.plot(X,Y_pred,c='red')
plt.show()

In [63]:
np.concatenate((Y,Y_pred),axis=1)

array([[22.1       , 20.52397441],
       [10.4       , 12.33785482],
       [ 9.3       , 12.30767078],
       [18.5       , 17.59782951],
       [12.9       , 13.18867186],
       [ 7.2       , 12.47834763],
       [11.8       , 11.72975995],
       [13.2       , 12.12295317],
       [ 4.8       ,  3.72734086],
       [10.6       , 12.55084872],
       [ 8.6       ,  7.0322992 ],
       [17.4       , 17.28512918],
       [ 9.2       , 10.57712073],
       [ 9.7       ,  8.82630048],
       [19.        , 18.43436638],
       [22.4       , 20.81929952],
       [12.5       , 12.82365674],
       [24.4       , 23.22495716],
       [11.3       ,  9.95168206],
       [14.6       , 14.16607293],
       [18.        , 18.10076728],
       [12.5       , 14.7405382 ],
       [ 5.6       ,  6.4891503 ],
       [15.5       , 16.5459329 ],
       [ 9.7       ,  8.14651887],
       [12.        , 15.6100386 ],
       [15.        , 14.98951429],
       [15.9       , 17.05167344],
       [18.9       ,

In [64]:
#Mean_absolute_error
np.abs(Y-Y_pred).mean()

1.252011229687068

In [52]:
#Mean Squared Error
((Y-Y_pred)**2).mean()

2.784569900338091

In [53]:
from sklearn import metrics
metrics.mean_absolute_error(Y,Y_pred)

1.2537471644234006

In [54]:
metrics.mean_squared_error(Y,Y_pred)

2.784569900338091

In [38]:
adv

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [0]:
corr = adv.corr()

In [66]:
corr

TV     radio  newspaper     sales
TV         1.000000  0.054809   0.056648  0.782224
radio      0.054809  1.000000   0.354104  0.576223
newspaper  0.056648  0.354104   1.000000  0.228299
sales      0.782224  0.576223   0.228299  1.000000

In [84]:
corr['sales'].sort_values(ascending=False)

sales        1.000000
newspaper    0.782224
radio        0.576223
TV           0.228299
Name: sales, dtype: float64

In [0]:
#Error optimization

In [0]:
x1 = 4
x2 = 6
Y = 35

In [0]:
m1 = 4
m2 = 6
lr = 0.001

In [130]:
Yp = m1*x1 + m2*x2
Yp

52

In [131]:
e = (Yp - Y)**2
print(e)

289


In [134]:
for i in range(50):
  Yp = m1*x1 + m2*x2

  dem1 = 2*(Y-Yp)*(-x1)
  dem2 = 2*(Y-Yp)*(-x2)

  m1 = m1 - lr * dem1
  m2 = m2 - lr * dem2

  e = (Y-Yp)**2
  print('m1:',m1,'m2:',m2,'error:',e)

m1: 3.7421439999999997 m2: 5.613216 error: 232.01382399999997
m1: 3.6329610239999997 m2: 5.449441536 error: 186.264410128384
m1: 3.5351330775039997 m2: 5.3026996162560005 error: 149.53604868162867
m1: 3.447479237443584 m2: 5.1712188561653765 error: 120.04993245839053
m1: 3.368941396749451 m2: 5.053412095124178 error: 96.37800657651519
m1: 3.298571491487508 m2: 4.947857237231263 error: 77.37380572773168
m1: 3.235520056372807 m2: 4.853280084559212 error: 62.11692921911464
m1: 3.179025970510035 m2: 4.768538955765054 error: 49.86846464797266
m1: 3.1284072695769916 m2: 4.6926109043654884 error: 40.03520131482691
m1: 3.0830529135409845 m2: 4.624579370311477 error: 32.14090017876407
m1: 3.042415410532722 m2: 4.563623115799084 error: 25.80322891791469
m1: 3.006004207837319 m2: 4.5090063117559795 error: 20.715245026964553
m1: 2.9733797702222375 m2: 4.460069655333358 error: 16.630530151567587
m1: 2.944148274119125 m2: 4.416222411178689 error: 13.351255694160935
m1: 2.917956853610736 m2: 4.376935

In [133]:

(Yp - Y)**2

232.01382399999997

In [96]:
0.001 * dem1

0.136

In [110]:
m1

3.447479237443584

In [116]:
m1

-132

In [117]:
dem1

136

In [122]:
m1 - (0.001 * dem1)

-132.136